# Generated by Django 4.0.4 on 2022-05-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('seed_depth', models.IntegerField()),
                ('seed_spacing', models.IntegerField()),
                ('water_cycle', models.CharField(max_length=255)),
                ('water_amount', models.CharField(max_length=255)),
                ('time_to_harvest', models.DateField()),
                ('harvested', models.BooleanField(default=False)),
                ('season', models.CharField(max_length=255)),
            ],
        ),
    ]
