# Generated by Django 4.0.4 on 2022-05-24 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='harvested',
        ),
    ]
