# Generated by Django 4.0.4 on 2022-05-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_remove_plant_harvested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='seed_depth',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='plant',
            name='seed_spacing',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='plant',
            name='time_to_harvest',
            field=models.CharField(max_length=255),
        ),
    ]
