# Generated by Django 4.0.4 on 2022-06-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPlants', '0002_alter_userplants_date_planted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplants',
            name='date_planted',
            field=models.DateField(),
        ),
    ]
