# Generated by Django 4.0.4 on 2022-06-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPlants', '0003_alter_userplants_date_planted'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplants',
            name='date_to_be_watered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userplants',
            name='days_between_watering',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
