# Generated by Django 4.0.4 on 2022-06-05 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPlants', '0004_userplants_date_to_be_watered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplants',
            name='date_to_be_watered',
            field=models.DateField(blank=True, null=True),
        ),
    ]
