# Generated by Django 4.0.4 on 2022-06-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPlants', '0005_alter_userplants_date_to_be_watered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplants',
            name='date_to_be_watered',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
